name: 🐞 Bug Report
description: Report a bug with ItemEra addon
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["klaufel/3"]
assignees:
  - klaufel
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug for ItemEra! Please fill out the information below to help us resolve the issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail. What did you expect to happen vs what actually happened?
      placeholder: |
        Example: The expansion filter in the bank doesn't work properly when I try to filter Wrath of the Lich King items... (screenshots, videos, etc.)
    validations:
      required: true
  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of ItemEra is affected?
      multiple: true
      options:
        - Tooltips (Expansion info display)
        - Bank Filter (Regular Bank)
        - Bank Filter (Reagent Bank)
        - Bank Filter (Account/Warband Bank)
        - Settings/Configuration
        - Localization/Language
        - Other
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce the bug
      placeholder: |
        1. Open the bank
        2. Click on the expansion filter dropdown
        3. Select "Wrath of the Lich King"
        4. Notice that items are not filtered correctly
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Items from Wrath of the Lich King should be highlighted and others should be dimmed
    validations:
      required: true
  - type: textarea
    id: other-addons
    attributes:
      label: Other Addons
      description: List other addons you have installed that might be related to this issue
      placeholder: |
        - Bagnon
        - BetterBags
        - ElvUI
        - WeakAuras
        - etc.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Error Messages or Console Output
      description: If you see any error messages in-game or in the console, paste them here
      render: lua
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have the latest version of ItemEra installed
          required: true
